services:
  db:
    image: postgres:16
    container_name: galonku-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokal
      POSTGRES_DB: galonku_db
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - '5431:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 20s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    environment:
      TZ: Asia/Jakarta
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 20s
      retries: 5

volumes:
  postgres_data:
  redis_data:
